apiVersion: 1
policies:
  - orgId: 1
    receiver: grafana-slack
    group_by: [ grafana_folder, alertname ]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 2h
    routes:
      - receiver: grafana-email
        object_matchers:
          - [ 'severity', '=', 'critical' ]